export const defaultHsm = {
  name: "Hsm",
  settings: {
    screenDpi: 97,
    epsilonMm: 0.1,
    magnetAttractionMm: 2,
    // magnetAttractionMm: 10,
    doubleClickTimeoutMs: 300,
    deltaMouseWheel: 120,
    deltaScale: 0.1,
    deltaScale2: 0.2,
    cursorMarginP: 8,
    stateRadiusMm: 4,
    // stateRadiusMm: 0,
    stateTitleHeightMm: 5,
    // stateTitleHeightMm: 0,
    stateMinWidthMm: 10,
    stateMinHeightMm: 10,
    minDistanceMm: 1,
    dragResetSpeed: 15,
    // initialTransLengthMm: 2,
    initialTransLengthMm: 10,
    defaultSegmentLengthMm: 10,
    smallestSegMm: 1,

    styles: {
      defaultColor: "grey",
      silhouetteSelected: "black",
      folioBackground: "seaShell",
      junction: {
        color: "brown",
        thicknessMm: 1.2,
        minLengthMm: 7,
        bgChroma: 50,
        trLight: 10,
        trChroma: 50,
        bgLight: 10,
        tagBorderChroma: 30,
        tagBorderLight: 95,
        tagTextSizeMm: 3,
        tagBgChroma: 10,
        tagBgLight: 95,
        tagBgOpacity: 0.5,
      },
      note: {
        marginP: 2,
        border: { color: "#DFDFDF", lineWidth: 1 },
        borderSelected: { color: "grey", lineWidth: 2 },
        bg: { color: "transparent" },
        bgSelected: { color: "white" },
        text: { heightMm: 3, color: "black", font: "sans-serif" },
        defaultFont: "Noto Sans",
        noteMinHeight: 3,
        noteMinWidth: 3,
        noteCornerP: 10,
      },
      state: {
        border: { chroma: 50, light: 30, lineWidth: 1 },
        borderError: { color: "red", lineWidth: 2 },
        borderSelected: { lineWidth: 2 },
        titleLine: { chroma: 50, light: 30, lineWidth: 1 },
        bg: { chroma: 30, light: 98 },
        titleBg: { chroma: 50, lights: [80, 95] },
        titleText: { chroma: 100, light: 5, font: "sans-serif", sizePc: 70 },
        info: {
          sizeMm: "2.5",
          font: "sans-serif",
          textColor: "black",
          backgroundColor: "transparent",
          marginMm: "2",
        },
      },
      text: {
        sizeMm: 2.5,
        textFont: "sans-serif",
        textChroma: 50,
        textLight: 10,
        borderWidth: 1,
        borderChroma: 30,
        borderLight: 95,
        // borderLight: 20,
        borderSelectedWidth: 1,
        borderSelectedChroma: 50,
        borderSelectedLight: 10,
        bgOpacity: 0.5,
      },
      tr: {
        line: { chroma: 100, light: 30, lineWidth: 1.5 },
        lineError: { color: "red", lineWidth: 2 },
        lineSelected: { lineWidth: 2.5 },
        errorDotRadiusMm: 3,
        maxTransRadiusMm: 4,
        arrowLengthMm: 3,
        arrowWidthMm: 0.75,
      },
      defaultColor: "darkorange",
    },
  },
  status: {
    serNum: 4,
    activeFolio: "F1",
  },
  folios:
    [
      {
        id: "F1",
        name: "Main Folio",
        geo: { x0: 0, y0: 0, width: 210, height: 297, scale: 1 },
      }
    ]
}

